
APPLICATION_URI = ''
CLIENT_ID = ''
CLIENT_SECRET = ''

SERVICE_URL = ''
AUTH_ENDPOINT = ''
CONNECTOR = ''
SERVICE_UPLOAD_URI = SERVICE_URL + 'connectors/' + CONNECTOR + '/upload/'
SERVICE_REFRESH_TOKEN_URI = SERVICE_URL + 'connectors/' + CONNECTOR + '/auth/refresh_token'

IDP_URI = ''
IDP_CLIENT_ID = ''
IDP_CLIENT_SECRET = ''
IDP_AUTHORIZATION_URI = IDP_URI+''
